version: '3'

tasks:
  up:
    desc: Dockerの起動
    cmds:
      - docker compose up -d
  down:
    desc: Dockerの終了
    cmds:
      - docker compose down
  build:
    desc: Docker build
    cmds:
      - docker compose build
  ssh:
    desc: ssh API Container
    cmds:
      - docker compose exec api /bin/bash
  mysql:
    desc: MySQLコンテナに入る mysql -u appuser -p でパスワード打つとログインできる
    cmds:
      - docker compose exec mysql /bin/bash
  downall:
    desc: volumeごと削除
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans
  reload:
    desc: FastAPIをreload
    cmds:
      - docker-compose exec api uvicorn main:app --reload
  pytest:
    desc: Testを実行する
    cmds:
      - docker-compose exec api pytest