version: '3'

# apiDockerFile単体で動かしたい時に使う
tasks:
  init:
    desc: 最初に実行する楽
    cmds:
      - docker build -t eiyama-app-runner-sample .
      - docker run -d --name eiyama-app-runner-sample -p 8080:8080 eiyama-app-runner-sample
  downall:
    desc: 全てを消しさる
    cmds:
      - docker stop eiyama-app-runner-sample
      - docker rm eiyama-app-runner-sample
      - docker rmi eiyama-app-runner-sample
  build:
    desc: docker imageのbuild
    cmds:
      - docker build -t eiyama-app-runner-sample .
  run:
    desc: run
    cmds:
      - docker run -d --name eiyama-app-runner-sample -p 8080:8080 eiyama-app-runner-sample
  stop:
    cmds:
      - docker stop eiyama-app-runner-sample
  rm:
    cmds:
      - docker rm eiyama-app-runner-sample
  rmi:
    cmds:
      - docker rmi eiyama-app-runner-sample
  health:
    desc: local healthCheck
    cmds:
      - curl http://localhost:8080
