version: '3'

# ECR+AppRunner用のコンテナを作る
tasks:
  downall:
    desc: 全てを消しさる
    cmds:
      - docker stop eiyama-app-runner-sample
      - docker rm eiyama-app-runner-sample
      - docker rmi eiyama-app-runner-sample
  build:
    desc: ECRにpushするためのdocker imageのbuild
    cmds:
      - docker build -t eiyama-app-runner-sample . --platform=linux/x86_64
  run:
    desc: 多分使わない
    cmds:
      - docker run -d --name eiyama-app-runner-sample -p 8080:8080 eiyama-app-runner-sample
  stop:
    cmds:
      - docker stop eiyama-app-runner-sample
  rm:
    cmds:
      - docker rm eiyama-app-runner-sample
  rmi:
    cmds:
      - docker rmi eiyama-app-runner-sample
